version: 1
disable_existing_loggers: False
formatters:
  simple:
    format: '%(asctime)s - %(name)s - %(levelname)s - %(message)s'
handlers:
  console:
    class: logging.StreamHandler
    level: DEBUG
    formatter: simple
    stream: ext://sys.stdout
loggers:
    bond.registry:
        level: DEBUG
        handlers: [console]
        propagate: no
    uvicorn:
        level: INFO
        handlers: [console]
        propagate: no
    gunicorn:
        level: INFO
        handlers: [console]
        propagate: no
root:
  level: INFO
  handlers: [console]
